// <auto-generated />
using APITesteConhecimento.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APITesteConhecimento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250516152858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreContato.Models.Contato", b =>
                {
                    b.Property<int>("id_contato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk_contato");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_contato"));

                    b.Property<string>("nome_contato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_contato");

                    b.Property<string>("telefone_contato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone_contato");

                    b.HasKey("id_contato");

                    b.ToTable("contatos");
                });
#pragma warning restore 612, 618
        }
    }
}
